services:
    gateway_nexon:
        build:
            context: .
            dockerfile: docker/docker.gateway_nexon
        ports:
            - "8001:8001"
        networks:
            - auth-serv
            - event-serv
        environment:
            - PORT=8001
            - HOST=localhost
            - AUTH_SERVICE_NAME=AUTH_SERVICE
            - AUTH_SERVICE_PORT=8081
            - AUTH_SERVICE_HOST=localhost
            - JWT_ACCESS_EXPIRES=60d
            - JWT_REFRESH_EXPIRES=180d
            - JWT_SECRET=JOIN_NEXON
            - COOKIEAGE=24 * 60 * 60 * 1000
            - EVENT_SERVICE_NAME=EVENT_SERVICE
            - EVENT_SERVICE_PORT=8082
            - EVENT_SERVICE_HOST=localhost
        depends_on:
            - auth_nexon
            - event_nexon
        # env_file:
        #     - gateway_nexon/.env
    auth_nexon:
        build:
            context: .
            dockerfile: docker/docker.auth_nexon
        ports:
            - "8081:8081"
        networks:
            - auth-serv
        environment:
            - PORT=8081
            - HOST=localhost
            - DB_URL=mongodb+srv://join_nexon_user:987987@joinnexon.ygtkmie.mongodb.net/?retryWrites=true&w=majority&appName=joinNexon
        # env_file:
        #     - auth_nexon/.env
        # environment:
        #     - PORT=8801
        #     - HOST=127.0.0.1

    event_nexon:
        build:
            context: .
            dockerfile: docker/docker.event_nexon
        ports:
            - "8082:8082"
        networks:
            - event-serv
        environment:
            - PORT=8082
            - HOST=localhost
            - DB_URL=mongodb+srv://join_nexon_user:987987@joinnexon.ygtkmie.mongodb.net/?retryWrites=true&w=majority&appName=joinNexon
        # env_file:
        #     - event_nexon/.env
networks:
    auth-serv:
    event-serv:
